In [2]:
#Q1

import numpy as np

In [10]:
#Project 1 

array = np.array(range(10))  #q1
print(array)
newarray = array.reshape(2,5)  #q2
print(newarray)
print(newarray.shape)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [9]:
#Q2 and Q3
arraythree = np.array(range(30,71))
print(arraythree)

arrayappended= np.append(arraythree,78)

print(arrayappended)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 78]


In [4]:
#Extension
print("Write a NumPy program to find the number of rows and columns of a given matrix.")

m = np.array(range(10,50,2)).reshape(4,5)
print(m)

print("The dimensions of this matrix is",m.shape)

print("Write a NumPy program to create an array of all the even integers from 30 to 70.")

n = np.array(range(30,71,2))
print(n)

Write a NumPy program to find the number of rows and columns of a given matrix.
[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
The dimensions of this matrix is (4, 5)
Write a NumPy program to create an array of all the even integers from 30 to 70.
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [8]:
#Extension Q3

print("Write a NumPy program to convert a list and tuple into arrays.")

mylist = [1,2,3,4,5,6,7,8,9,10]
print("The list:")
print(mylist)
x = np.asarray(mylist)
print("The list now converted to an array:")
print(x)
mytuple = ([8,4,3],[4,2,6])
print("The tuple:")
print(mytuple)
n = np.asarray(mytuple)
print("The tuple now converted to an array")
print(n)


Write a NumPy program to convert a list and tuple into arrays.
The list:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The list now converted to an array:
[ 1  2  3  4  5  6  7  8  9 10]
The tuple:
([8, 4, 3], [4, 2, 6])
The tuple now converted to an array
[[8 4 3]
 [4 2 6]]


In [3]:
#Extension Q4

data_type = [('name', 'S15'), ('class', int), ('height', float)] 

students_details = [('James', 5,
48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]


x = np.asarray(students_details)

print(x)

print(np.sort(x,0))


[['James' '5' '48.5']
 ['Nail' '6' '52.5']
 ['Paul' '5' '42.1']
 ['Pit' '5' '40.11']]
[['James' '5' '40.11']
 ['Nail' '5' '42.1']
 ['Paul' '5' '48.5']
 ['Pit' '6' '52.5']]
