In [30]:
pip install mysql-connector-python

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\dakin\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [23]:
import mysql.connector #Used for connecting to SQL
import numpy as np  

db_connection = mysql.connector.connect(

host="localhost",user="root",passwd="Ddjcc568" , database="uni")   #connect to database

In [24]:
databases = db_connection.cursor() # setup for connection string
databases.execute("Select joiningfee,membershipfee,equipmentfee from uni.club")
result_table = databases.fetchall() # fetches all the rows of a query result
array = np.asarray(result_table)
print("I will now print the joining,membership and equipment fees as matrix:")
print(array)
e = np.sum(array, axis = 1)
print("The total cost of the joining, membership and equipment fee by club is the value of each element in the matrix")
print(e)




I will now print the joining,membership and equipment fees as matrix:
[[ 10   0   0]
 [ 10  20  10]
 [ 10  20  50]
 [ 10  10   0]
 [ 10  10   0]
 [ 10  20   0]
 [ 10  30  15]
 [ 20  50 150]
 [ 10  10  10]
 [ 50 200  25]
 [ 10  10  10]
 [ 10  10   0]
 [ 10  10   0]
 [ 20  10   0]
 [ 30 100 250]
 [ 10  10   5]
 [ 20  10   5]
 [ 10  10   0]
 [ 20  10 100]
 [ 40  20 175]
 [ 10  10 150]
 [ 10  10   0]
 [ 10  25  60]
 [ 20  20  10]
 [ 10  20   0]
 [ 10  10 150]
 [ 10  10  75]
 [ 10  10  60]
 [ 10  20  45]
 [ 10  10  65]]
The total cost of the joining, membership and equipment fee by club is the value of each element in the matrix
[ 10  40  80  20  20  30  55 220  30 275  30  20  20  30 380  25  35  20
 130 235 170  20  95  50  30 170  95  80  75  85]


In [6]:
databases = db_connection.cursor() # setup for connection string
databases.execute("SELECT (fulltimefee-scholarshipdiscount) FROM uni.fees")
result_table = databases.fetchall() # fetches all the rows of a query result
array = np.asarray(result_table)
print(array)

[[10500]
 [ 5500]
 [ 9400]
 [10450]
 [ 2000]
 [10200]
 [ 5700]
 [ 5800]
 [10000]
 [ 6000]
 [ 9850]
 [ 7200]]


In [28]:
databases = db_connection.cursor() # setup for connection string
databases.execute("SELECT classid, min(feedbackscore) as minfeed FROM uni.schedule")
result_table = databases.fetchall() # fetches all the rows of a query result
print(result_table)   #Prints the Class ID with the lowest feedback score? 

[(1, 2)]


In [29]:
databases = db_connection.cursor() # setup for connection string
databases.execute("SELECT classid, max(feedbackscore) as maxfeed FROM uni.schedule")
result_table = databases.fetchall() # fetches all the rows of a query result
print(result_table)   #Prints the Class ID with the highest feedback score? 

[(1, 10)]
