In [2]:
#Project 2 Mathematics 
import numpy as np

In [3]:
#Q1

print("Adding")
print(np.add(1, 4.))
print("Subtracting:")
print(np.subtract(1, 4))
print("Multiplying:")
print(np.multiply(1, 4))
print("Dividing:")
print(np.divide(1, 4))

Adding
5.0
Subtracting:
-3
Multiplying:
4
Dividing:
0.25


In [5]:
#Q2
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.7])
print("Here is an array of numbers, with each element being a float")
print(x)
x = np.rint(x)
print("Now, I am going round each element to the nearest integer")
print(x)

Here is an array of numbers, with each element being a float
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2.7]
Now, I am going round each element to the nearest integer
[-1. -2. -2.  0.  2.  2.  3.]


In [6]:
#Q3
x = np.arange(10)
print("An array with elements from 0 to 9")
print(x)
print("Division of the array inputs, element-wise, (Divides every element by 2")
print(np.true_divide(x,2))  #Found on the interent, this just divides every element by the number put in the true divide function?

An array with elements from 0 to 9
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise, (Divides every element by 2
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [8]:
#Extension
n = np.array(range(1,16)).reshape(5,3)   #Q1
m = np.array(range(1,7)).reshape(3,2)
print("Here is my matrix n:")
print(n)
print("Here is my matrix m")
print(m)

print("Now here is the matrix n*m, note order is important, Matrix multiplication is not commutative:")

nm = np.dot(n,m)

print(nm)


Here is my matrix n:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Here is my matrix m
[[1 2]
 [3 4]
 [5 6]]
Now here is the matrix n*m, note order is important, Matrix multiplication is not commutative:
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


In [14]:
x = np.random.randn(1000) #This function creates an array with 1000 elements
print("Average of the array elements:")
average = np.mean(x)
print(average)
print("Standard deviation of the array elements:")
standarDev = np.std(x)
print(standarDev)
print("Variance of the array elements:")
variance = np.var(x)
print(variance)



Average of the array elements:
-0.008939450267208791
Standard deviation of the array elements:
1.0078985710335349
Variance of the array elements:
1.0158595294914416


In [23]:
x = np.array([1.5,6.6,7.8,4.3,2.6,9.3])
print("Original array: ")
print(x)
r1 = np.around(x,5) #This rounds each element to the specified no. of decimal places, in  this case 5
r2 = np.floor(x)   #Just gives the the element in the 'ones unit' of the float?
r3 = np.ceil(x)   
r4 = np.trunc(x)
r5 = [round(elem) for elem in x]

print("\naround:   ", r1)
print("floor:    ",r2)
print("ceil:     ",r3)
print("trunc:    ",r4)
print("round:    ",r5)

Original array: 
[1.5 6.6 7.8 4.3 2.6 9.3]

around:    [1.5 6.6 7.8 4.3 2.6 9.3]
floor:     [1. 6. 7. 4. 2. 9.]
ceil:      [ 2.  7.  8.  5.  3. 10.]
trunc:     [1. 6. 7. 4. 2. 9.]
round:     [2, 7, 8, 4, 3, 9]


In [24]:
x =  np.random.rand(10)

print(x)

mini = np.amin(x)
maxi = np.amax(x)

print("The min value of the array is",mini,"and the max is",maxi)

[0.51008289 0.59203028 0.6704177  0.99875581 0.07175354 0.26918123
 0.63860419 0.19158247 0.69505388 0.24218822]
The min value of the array is 0.0717535366893618 and the max is 0.9987558052855408
